# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

workspace '../kocomojo'

target 'KocomojoKit' do

pod 'AFNetworking', '~> 2.5'

end

target 'KocomojoKitTests' do

end

